#!/bin/bash
. "$(dirname "$0")/common.sh"

# check if branch is protected (production or staging)
if [[ $current_branch != "$production_branch" && $current_branch != "$staging_branch" ]] ; then
    print "Branch \"${current_branch}\" is NOT protected" $BLUE
    exit 0;
fi

print "Branch \"${current_branch}\" is protected" $BLUE

print "Running lint:check..." $BLUE
npm run lint:check
if [ $? != 0 ]; then
  exit 1
fi

print "Updating patch version" $BLUE
yarn version --patch

exit 0