#!/bin/bash
. "$(dirname "$0")/common.sh"

# check if branch is protected (production or staging)
if [[ $current_branch != "$production_branch" && $current_branch != "$staging_branch" ]] ; then
    print "Branch \"${current_branch}\" is NOT protected" $GREEN
    exit 0;
fi

print "Branch \"${current_branch}\" is protected" $YELLOW
print "Running pre push check..." $YELLOW

# check lint and type errors
npm run lint:check
if [ $? != 0 ]; then
  exit 1
fi

# check build command
#npm run build
#if [ $? != 0 ]; then
#  exit 1
#fi


print "Pre push check passed" $GREEN

print "Updating version" $GREEN
yarn version --patch

exit 0